### PR TITLE
Set host tags

### PR DESCRIPTION
**Pull request by voelzmo**
* switch to p-helper style for accessing manifest properties to ensure errors are properly raised. See http://bosh.io/docs/jobs.html#properties
* define defaults for optional properties apitoken and evironment id
* write host tags to `/var/lib/dynatrace/oneagent/config/hostautotag.conf` or empty the file

### CODE REVIEW

**Comment by arthfl** [comment]
Thanks for your PR!

We're currently in the process of finishing the general refactoring of the bosh release, so it might take 2-3 weeks before we can merge your pull-request.

**Comment by voelzmo** [comment]
Thanks for managing my expectations, @arthfl ;)

**Comment by voelzmo** [comment]
Hey @arthfl what's your current state on the refactoring? Any chances to get these changes in?

**Comment by voelzmo** [comment]
Merged master back in to resolve conflicts

**Comment by voelzmo** [comment]
Hey @arthfl any chance to merge this in or is there anything I should change for that feature?

**Comment by voelzmo** [comment]
ping @arthfl any progress on including this in the master?

**Comment by danirabiser** [comment]
Hi @voelzmo ,

thanks for submitting this PR. We would be interested in the use case you want to support with this PR. For what type of hosts would you like to set the host tags? Are these host tags already specified e.g., on runtime config level (https://bosh.io/docs/manifest-v2/#tags)?

Thanks,
Daniela

**Comment by lrgar** [comment]
Thank you for your PR, it has been merged now. Among the changes, host_tags is now hosttags for consistency with other parameters.

**Pull request merged**
