### PR TITLE
Set Host Names

### PR DESCRIPTION
**Pull request by Espe0n**
Dynatrace allows to set custom host names by adding a host name configuration file as mentioned in: 

https://www.dynatrace.com/support/help/infrastructure/hosts/how-do-i-set-custom-host-names-in-dynamic-environments/

In this PR we try to make this Feature available for the bosh-oneagent-release.

### CODE REVIEW

**Comment by danirabiser** [comment]
Hi @Espe0n,

thanks for submitting this PR. We would be interested in the use case you want to support with this PR. For what type of hosts would you like to set the host names?

Thanks,
Daniela

**Comment by Espe0n** [comment]
Hi,
Thanks for you answer.

At the Moment Dynatrace uses a autodetected Hostname (instance-name + number) or, if used, reads the VM-Name from AWS (normally the instance-name followed by the UUID). However, this does not Help to understand, what this Host is used for, at the first glance. Apart from readability, a meaningful hostname can already provide much information that would otherwise have to be found out from the context (tags, properties).

For example: Is it a test system, a development-system or a productive System.

Best Regards,
	Christoph

**Comment by danirabiser** [comment]
Hi Christoph,

thanks for the clarification. We are planning to change the auto-detected host name for Cloud Foundry VMs to BOSH name/BOSH id (e.g., router/2ba57e41-42e3-4a7a-b615-6d77c73661d7). However, if I understand your use case description correctly, then you'd want to rename Cloud Foundry VMs to some naming scheme that indicates the purpose of a host, e.g., if it belongs to a testing, a development or a production system? Are you adding a prefix to the auto-detected host name?

Thanks,
Daniela

**Comment by danirabiser** [comment]
Hi Christoph,

sorry for the late response and thanks for clarifying your use case.

Our recommendation to optimally cover your use case would be to set the desired host name (in your case System-ID followed by the Instance-Name) via the recently introduced property `hostprops` which will be available with the upcoming release of the Dynatrace OneAgent BOSH add-on. The property `hostprops` allows you to define a custom property for your BOSH-managed VMs.

Your custom property will then show up under host properties which can be used within **host naming rules**. Host naming rules work similar to service or process group naming rules in Dynatrace. However, please note that although host naming rules are around the corner it will take 2-3 sprints to release this capability.  

Hope this helps.

Thanks,
Daniela

**Pull request closed without merging**
